### ISSUE TITLE
autocomplete("SELECT ") throws error - [RangeError]: token index 1 out of range 0..0

### ISSUE THREAD

**Issue by hocopor** [modeldba/sql-autocomplete#1]
Hello. Thanks for your package. Unfortunately, I have not been able to use it yet. 

"RangeError]: token index 1 out of range 0..0" occurs when a space is encountered in sql string. Well, let's look at an example.
[Codesandbox](https://codesandbox.io/s/sql-autocomplete-example-qitii?file=/src/index.js)

String `"SELECT"` works fine.
String `"SELECT "` throws an exception like `RangeError: token index 1 out of range 0..0`.

Your examples from the readme file also do not work, but when I cloned the repository and ran the tests, they all succeeded.

Could you please shed some light on this issue?

**Comment by mtriff** [comment]
Thanks for reporting! It looks like one of the dependencies released an update and that has resulted in a conflict with another dependency. 

I'll release an updated version in the next couple days, but in the meantime, you can get around this by running:
```
npm install antlr4-c3@1.1.12
```

**Comment by mtriff** [comment]
Sorry, this took a bit longer than expected to debug. This has been fixed in version 1.1.0.
