### ISSUE TITLE
Could not resolve "assert" when installing

### ISSUE THREAD

**Issue by olimart** [modeldba/sql-autocomplete#3]
I would like to use this library in the browser.

When importing through `import { SQLAutocomplete, SQLDialect } from 'sql-autocomplete'`
It raises the following error:

```
> node_modules/antlr4ts/atn/LexerATNSimulator.js:34:23: error: Could not resolve "assert" (use "--platform=node" when building for node)
js     |     34 │ const assert = require("assert");
```

Is the library meant to work only for node apps? Else, can you please advise. Thanks.

**Comment by mtriff** [comment]
Unfortunately, this library relies on antlr4ts, which requires Node. I don't know if it's possible to get it working in the browser.

**Comment by olimart** [comment]
ok thanks.
